import "./controls/carousel.js";
import "./controls/instagram.js";
import "./controls/product-list.js";
import "./controls/product-tab.js";
import "./controls/product-list-with-banner.js";
import "./controls/brand.js";
import "./controls/product-tab-with-banner.js";
import "./controls/policy.js";
import "./controls/featured.js";
import "./controls/collection.js";
import "./components/buttonProductModal.js";
import "./controls/latest-post.js";
import "./controls/collection-countdown.js";
import "./controls/xmas/xmas-carousel.js";
import "./controls/xmas/xmas-customer.js";
import "./controls/xmas/xmas-policy.js";
import "./controls/parallaxControl.js";
import "./controls/xmas/xmas-mc-customizer.js";
import buttonInstagramLoadMore from "./components/buttonInstagramLoadMore.js";

buttonInstagramLoadMore();